[project]
name = "testconstructor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosmtplib==4.0.1",
    "alembic==1.15.1",
    "annotated-types==0.7.0",
    "anyio==4.8.0",
    "asyncpg==0.30.0",
    "black==25.1.0",
    "cffi==1.17.1",
    "click==8.1.8",
    "colorama==0.4.6",
    "cryptography==44.0.2",
    "dnspython==2.7.0",
    "dotenv==0.9.9",
    "email-validator==2.2.0",
    "fastapi==0.115.11",
    "greenlet==3.1.1",
    "h11==0.14.0",
    "idna==3.10",
    "mako==1.3.9",
    "markupsafe==3.0.2",
    "mypy-extensions==1.0.0",
    "packaging==24.2",
    "passlib==1.7.4",
    "pathspec==0.12.1",
    "platformdirs==4.3.6",
    "pycparser==2.22",
    "pydantic==2.10.6",
    "pydantic-core==2.27.2",
    "pydantic-settings==2.8.1",
    "pyjwt==2.10.1",
    "python-dotenv==1.0.1",
    "python-multipart==0.0.20",
    "redis==5.2.1",
    "sniffio==1.3.1",
    "sqlalchemy==2.0.38",
    "starlette==0.46.1",
    "typing-extensions==4.12.2",
    "uv==0.7.8",
    "uvicorn==0.34.0",
]
