"""Fix keys

Revision ID: 7cf2ef32a426
Revises: 9cadbc475ba3
Create Date: 2025-03-22 11:30:59.677859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cf2ef32a426"
down_revision: Union[str, None] = "9cadbc475ba3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "results", ["tested_user_id"])
    op.drop_constraint("tested_users_result_id_fkey", "tested_users", type_="foreignkey")
    op.drop_column("tested_users", "result_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tested_users",
        sa.Column("result_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "tested_users_result_id_fkey", "tested_users", "results", ["result_id"], ["id"]
    )
    op.drop_constraint(None, "results", type_="unique")
    # ### end Alembic commands ###
