"""Create table tested_user

Revision ID: 1379e38a553d
Revises: 7c37ffa6d12d
Create Date: 2025-03-19 22:34:17.575861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1379e38a553d"
down_revision: Union[str, None] = "7c37ffa6d12d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tested_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("result_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tested_users_email"), "tested_users", ["email"], unique=True
    )
    op.add_column("results", sa.Column("tested_user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "results", "tested_users", ["tested_user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "results", type_="foreignkey")
    op.drop_column("results", "tested_user_id")
    op.drop_index(op.f("ix_tested_users_email"), table_name="tested_users")
    op.drop_table("tested_users")
    # ### end Alembic commands ###
