"""Add param passing score

Revision ID: 30e596b013d1
Revises: 7cf2ef32a426
Create Date: 2025-04-02 15:30:36.895639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30e596b013d1"
down_revision: Union[str, None] = "7cf2ef32a426"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("results", sa.Column("score_passed", sa.Boolean(), nullable=False))
    op.add_column("tests", sa.Column("passing_score", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tests", "passing_score")
    op.drop_column("results", "score_passed")
    # ### end Alembic commands ###
