"""Create tables without user role

Revision ID: 69381782b56e
Revises: 4516f9c324b5
Create Date: 2025-03-17 21:01:49.983083

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69381782b56e"
down_revision: Union[str, None] = "4516f9c324b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("role", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
