"""Add duration to test

Revision ID: 6a230117fe94
Revises: 30e596b013d1
Create Date: 2025-04-20 22:09:06.435485

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a230117fe94"
down_revision: Union[str, None] = "30e596b013d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tests", sa.Column("duration", sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tests", "duration")
    # ### end Alembic commands ###
