"""email not unique

Revision ID: cf48bcd91367
Revises: 6a230117fe94
Create Date: 2025-05-20 20:33:26.745052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf48bcd91367"
down_revision: Union[str, None] = "6a230117fe94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tested_users_email", table_name="tested_users")
    op.create_index(
        op.f("ix_tested_users_email"), "tested_users", ["email"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tested_users_email"), table_name="tested_users")
    op.create_index("ix_tested_users_email", "tested_users", ["email"], unique=True)
    # ### end Alembic commands ###
