"""Create table tested_user

Revision ID: 9cadbc475ba3
Revises: 1379e38a553d
Create Date: 2025-03-20 10:02:36.599967

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9cadbc475ba3"
down_revision: Union[str, None] = "1379e38a553d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tested_users", sa.Column("score", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tested_users", "score")
    # ### end Alembic commands ###
